import { Prisma } from '@prisma/client';
import { hashSync } from 'bcryptjs';

import { USERS } from '../consts';

export const userData: Prisma.UserCreateManyInput[] = [
  {
    id: USERS[0],
    username: 'james',
    fullname: 'James Reynolds',
    sponsorName: 'BlackRifle',
    introducerFullName: 'Rob Reynolds',
    mobile: '+1 5052121515',
    assetId: 'oVPDrB',
    txcPayout: '$TXC-Cold',
    txcCold: 'ToVPDrBvSUFrdZasJrz9EXmdENBrt2g3bb',
    email: 'vitovodenko@gmail.com',
    password: hashSync('123456789', 12),
    address: '123',
    isAdmin: false,
  },
  {
    id: USERS[1],
    username: 'finix',
    fullname: 'Golden Finix',
    mobile: '+1 9478861998',
    assetId: 'OvpdRb',
    txcPayout: '$TXC-Cold',
    txcCold: 'ToVPDrBvSUFrdZasJrz9EXmdENBrt2g3bb',
    email: 'goldenfinix@outlook.com',
    password: hashSync('123456789', 12),
    isAdmin: true,
    address: '123',
  },
  {
    id: USERS[2],
    username: 'CryptoCowboy',
    fullname: 'Josh Simpson',
    mobile: '+1 2088818120',
    email: 'intelustry@gmail.com',
    sponsorName: 'texitoz',
    introducerFullName: 'Abraham Day',
    assetId: 'uUhDsV',
    txcPayout: '$TXC-Cold',
    txcCold: 'TuUhDsV4mw2V65ujSQwfboy27odR3EMQRT',
    password: hashSync('123456789', 12),
    isAdmin: false,
    address: '1219 W Zenith Cir',
  },
  {
    id: USERS[3],
    username: 'lissa',
    fullname: 'Lissa Bostick',
    mobile: '+1 9729771903',
    email: 'musicwlissa@att.net',
    sponsorName: 'johnny',
    introducerFullName: 'Johnny Bostick',
    assetId: 'aPybmh',
    txcPayout: '$TXC-Cold',
    txcCold: 'TaPybmhHU6tHY5F7aKCPV1TBQbotZdadgc',
    password: hashSync('123456789', 12),
    isAdmin: false,
    address: '241 rose garden',
  },
  {
    id: USERS[4],
    username: 'stepheb',
    fullname: 'Stephen Land',
    mobile: '+1 2142706402',
    email: 'crankshaft3008@gmail.com',
    sponsorName: 'portch',
    introducerFullName: 'Matt Portch',
    assetId: 'rR25ha',
    txcPayout: '$TXC-Cold',
    txcCold: 'TrR25haLcJFTHashiHoxLyK4btsJGkzLp4',
    password: hashSync('123456789', 12),
    isAdmin: false,
    address: '306 Oak Ridge Place',
  },
  {
    id: USERS[5],
    username: '06072479',
    fullname: 'Scott Cheuvront',
    mobile: '+1 6159721719',
    email: 'exoticmetals@comcast.net',
    sponsorName: 'TexitFreedom',
    introducerFullName: 'Chris Beck',
    assetId: 'vzsARu',
    txcPayout: '$TXC-Cold',
    txcCold: 'TvzsARuJSnJVaTAGDjkbvJCmWWZxp5wEfG',
    password: hashSync('123456789', 12),
    isAdmin: false,
    address: '301 Northcreek Blvd Unit 282',
  },
  {
    id: USERS[6],
    username: 'JulieAstbury',
    fullname: 'Julie Astbury',
    mobile: '+1 9729891287',
    email: 'jastbury@sbcglobal.net',
    sponsorName: 'BlackRifle',
    introducerFullName: 'Rob Reynolds',
    assetId: 'cc3AR5',
    txcPayout: '$TXC-Cold',
    txcCold: 'Tcc3AR5neB7jDuSawEupZcbcwfThCtrcoY',
    password: hashSync('123456789', 12),
    isAdmin: false,
    address: '516 Forest Edge',
  },
  {
    id: USERS[7],
    username: 'griswold',
    fullname: 'Chris Griswold',
    mobile: '+1 4052297595',
    email: 'chris@chrisgriswoldpc.com',
    sponsorName: 'MajaStarner',
    introducerFullName: 'Maja Starner',
    assetId: 'pQw9ZL',
    txcPayout: '$TXC-Cold',
    txcCold: 'TpQw9ZLx74JcSF5JgxPQfFFAfDXa2vMNt2',
    password: hashSync('123456789', 12),
    isAdmin: false,
    address: '1105 Myrtle Drive',
  },
  {
    id: USERS[8],
    username: 'whiskeytwonine',
    fullname: 'Dustyn Anthony',
    mobile: '+1 9729774399',
    email: 'dustynanthony@yahoo.com',
    sponsorName: 'Redline',
    introducerFullName: 'Jimmy Brown',
    assetId: 'gKUtmd',
    txcPayout: '$TXC-Cold',
    txcCold: 'TgKUtmdqnkBk75NBuF2y53BSKiTpUBZY2r',
    password: hashSync('123456789', 12),
    isAdmin: false,
    address: '206 S FM 55',
  },
  {
    id: USERS[9],
    username: 'gaige',
    fullname: 'Gaige Blake',
    mobile: '+1 6603732340',
    email: 'gaigeblake2015@gmail.com',
    sponsorName: 'minetxc',
    introducerFullName: 'Bobby Gray',
    assetId: 'iBsxbZ',
    txcPayout: '$TXC-Cold',
    txcCold: 'TiBsxbZCVWgfGL6kYv1w1xZiQhTBWRBpQD',
    password: hashSync('123456789', 12),
    isAdmin: false,
    address: 'Atlas Spas',
  },
  {
    id: USERS[10],
    username: 'putman',
    fullname: 'Mark Puttman',
    mobile: '+1 8067905085',
    email: 'markputman@yahoo.com',
    sponsorName: 'randy',
    introducerFullName: 'Randy Hancock',
    assetId: 'bmR2hP',
    txcPayout: '$TXC-Cold',
    txcCold: 'TbmR2hPpmscejW88edhqGZF9ju8gAPY3SC',
    password: hashSync('123456789', 12),
    isAdmin: false,
    address: '4605 64th',
  },
  {
    id: USERS[11],
    username: 'kalistarner',
    fullname: 'Kali Starner',
    mobile: '+1 1231234567',
    email: 'kali@starner.com',
    sponsorName: 'MajaStarner',
    introducerFullName: 'Maja Starner',
    assetId: 'ts7nB2',
    txcPayout: '$TXC-Cold',
    txcCold: 'Tts7nB2DRD8gVVJf7vxGvipJC4gTy8D8MV',
    password: hashSync('123456789', 12),
    isAdmin: false,
    address: '123',
  },
];
