-- AlterTable
ALTER TABLE "balances" ALTER COLUMN "date" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "note" DROP NOT NULL,
ALTER COLUMN "amountInCents" SET DEFAULT 0,
ALTER COLUMN "balanceInCents" SET DEFAULT 0;
